services:
  - type: web
    name: lstm-bitcoin-predict
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn web_app.main:app --host 0.0.0.0 --port $PORT
    plan: free